apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: docker-lab
type: Opaque
stringData:
  DB_USER: app_user
  DB_PASSWORD: app_password
  DB_NAME: tasksdb
  MYSQL_ROOT_PASSWORD: rootpassword